### ISSUE TITLE
Unresolved reference: PrivateConstants

### ISSUE THREAD

**Issue by shipsywor** [zhufree/SCP-Android#9]
After trying to compile the app, got this error:

```
e: D:\SCP-Android\app\src\main\java\info\free\scp\ScpApplication.kt: (34, 32): Unresolved reference: PrivateConstants
```

Line 34 mentioned in the above error is: https://github.com/zhufree/SCP-Android/blob/6387b80423a8347755bf458b2a2ed61a153fe7cb/app/src/main/java/info/free/scp/ScpApplication.kt#L34

How do I fix this error and where is `PrivateConstants`?

Also, how do I get `APP_ID` and `API_KEY` key mentioned in the below code in `ApiService.k`

```
PrivateConstants.APP_ID,
PrivateConstants.API_KEY,

```

Please add usage instructions to compile the app.

**Comment by zhufree** [comment]
`UMConfigure.init` this line is used for init a data analyze lib, the PrivateConstants is a private file to store some private key so I won't push it to github, you can make a PrivateConstants.kt file and put some random string, ( I think the code will log some error info but won't crash

**Comment by zhufree** [comment]
and the APP_ID and APP_KEY is used to get info on a saas platform https://bmob.cn, you can register and create your own app on it then get your APP_ID and APP_KEY
